Repository altlinux/gpupdate, pull requests merged in 2020-06, with the labels that each got.

#78 Another package install implementation
  gpoa/frontend/frontend_manager.py
  gpoa/frontend/package_applier.py
  gpoa/gpt/gpt.py
  gpoa/test/frontend/appliers/test_packages.py
  gpoa/util/rpm.py
Labels: enhancement

#82 Use USER variable instead of unstable AUTOFS_UID
  gpoa/templates/autofs_mountpoints.j2
Labels: bug

#81 Enable Printers.xml parser and merger
  gpoa/frontend/cups_applier.py
  gpoa/gpt/gpt.py
  gpoa/gpt/printers.py
  gpoa/storage/record_types.py
Labels: enhancement

#84 KRB5CCACHE destroy
  gpoa/gpoa
  gpoa/util/kerberos.py
  gpoa/util/signals.py
  gpupdate.spec
Labels: bug

#83 Add user policy implementation for deny all removable storages
  gpoa/frontend/appliers/polkit.py
  gpoa/frontend/frontend_manager.py
  gpoa/frontend/polkit_applier.py
  gpoa/templates/48-gpoa_disk_permissions_user.rules.j2
  gpoa/templates/49-gpoa_disk_permissions.rules.j2
Labels: enhancement

#85 gpoa: Fixed KRB5CCNAME usage
  gpoa/gpoa
Labels: bug

#77 Error codes
  gpoa/gpupdate
  gpoa/messages/__init__.py
Labels: enhancement

#90 sqlite_registry: Fixed samba_hkcu_preg mapping in query
  gpoa/storage/sqlite_registry.py
Labels: bug, critical

#91 Fix TALLOC ownership problem in PReg parser
  gpoa/util/preg.py
Labels: bug, critical

#88 Experimental frontend modules' switch
  .gitignore
  gpoa/frontend/applier_frontend.py
  gpoa/frontend/chromium_applier.py
  gpoa/frontend/cifs_applier.py
  gpoa/frontend/control_applier.py
  gpoa/frontend/cups_applier.py
  gpoa/frontend/firefox_applier.py
  gpoa/frontend/folder_applier.py
  gpoa/frontend/frontend_manager.py
  gpoa/frontend/gsettings_applier.py
  gpoa/frontend/package_applier.py
  gpoa/frontend/polkit_applier.py
  gpoa/frontend/shortcut_applier.py
  gpoa/frontend/systemd_applier.py
Labels: enhancement

#79 Firewall applier
  gpoa/frontend/appliers/firewall_rule.py
  gpoa/frontend/firewall_applier.py
  gpoa/frontend/frontend_manager.py
Labels: enhancement

#92 Switch fixes
  gpoa/frontend/applier_frontend.py
  gpoa/frontend/polkit_applier.py
Labels: bug

#93 Check kinit and kdestroy for errors
  gpoa/gpoa
  gpoa/util/arguments.py
  gpoa/util/kerberos.py
Labels: enhancement
